--------------------------------------------------------
--  File created - Friday-May-12-2017
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SIM_SACT_CYCLE
--------------------------------------------------------

  CREATE TABLE "SIM_SACT_CYCLE" 
   (	"MERGED_CYCLE_ID" NUMBER(19,0) NOT NULL, 
	"MERGED_REGIMEN_ID" NUMBER(19,0), 
	"CYCLE_NUMBER" NUMBER(10,0), 
	"START_DATE_OF_CYCLE" DATE, 
	"OPCS_PROCUREMENT_CODE" VARCHAR2(4), 
	"PERF_STATUS_START_OF_CYCLE" VARCHAR2(2), 
	"MERGED_PATIENT_ID" NUMBER(19,0), 
	"MERGED_TUMOUR_ID" NUMBER(19,0),
	PRIMARY KEY(MERGED_CYCLE_ID)
   ) ;

--   ALTER TABLE "SIM_SACT_CYCLE" MODIFY ("MERGED_CYCLE_ID" NOT NULL ENABLE);
--   ALTER TABLE "SIM_SACT_CYCLE" ADD CONSTRAINT PK_SIM_SACT_CYCLE PRIMARY KEY (MERGED_CYCLE_ID);

--------------------------------------------------------
--  DDL for Table SIM_SACT_DRUG_DETAIL
--------------------------------------------------------

  CREATE TABLE "SIM_SACT_DRUG_DETAIL" 
   (	"MERGED_DRUG_DETAIL_ID" NUMBER(19,0) NOT NULL, 
	"MERGED_CYCLE_ID" NUMBER(19,0), 
	"ORG_CODE_OF_DRUG_PROVIDER" VARCHAR2(5), 
	"ACTUAL_DOSE_PER_ADMINISTRATION" NUMBER(10,3), 
	"OPCS_DELIVERY_CODE" VARCHAR2(4), 
	"ADMINISTRATION_ROUTE" NUMBER(10,0), 
	"ADMINISTRATION_DATE" DATE, 
	"MERGED_PATIENT_ID" NUMBER(19,0), 
	"MERGED_TUMOUR_ID" NUMBER(19,0), 
	"MERGED_REGIMEN_ID" NUMBER(19,0), 
	"DRUG_GROUP" VARCHAR2(500),
	PRIMARY KEY(MERGED_DRUG_DETAIL_ID)
   ) ;

--   ALTER TABLE "SIM_SACT_DRUG_DETAIL" MODIFY ("MERGED_DRUG_DETAIL_ID" NOT NULL ENABLE);
--   ALTER TABLE "SIM_SACT_DRUG_DETAIL" ADD CONSTRAINT PK_SIM_SACT_DRUG_DETAIL PRIMARY KEY (MERGED_DRUG_DETAIL_ID);

--------------------------------------------------------
--  DDL for Table SIM_SACT_OUTCOME
--------------------------------------------------------

  CREATE TABLE "SIM_SACT_OUTCOME" 
   (	"MERGED_OUTCOME_ID" NUMBER(19,0) NOT NULL, 
	"MERGED_REGIMEN_ID" NUMBER(19,0), 
	"DATE_OF_FINAL_TREATMENT" DATE, 
	"REGIMEN_MOD_DOSE_REDUCTION" VARCHAR2(1), 
	"REGIMEN_MOD_TIME_DELAY" VARCHAR2(1), 
	"REGIMEN_MOD_STOPPED_EARLY" VARCHAR2(1), 
	"REGIMEN_OUTCOME_SUMMARY" VARCHAR2(1), 
	"MERGED_PATIENT_ID" NUMBER(19,0), 
	"MERGED_TUMOUR_ID" NUMBER(19,0),
	PRIMARY KEY(MERGED_OUTCOME_ID)
   ) ;

--   ALTER TABLE "SIM_SACT_OUTCOME" MODIFY ("MERGED_OUTCOME_ID" NOT NULL ENABLE);
--   ALTER TABLE "SIM_SACT_OUTCOME" ADD CONSTRAINT PK_SIM_SACT_OUTCOME PRIMARY KEY (MERGED_OUTCOME_ID);

--------------------------------------------------------
--  DDL for Table SIM_SACT_PATIENT
--------------------------------------------------------

  CREATE TABLE "SIM_SACT_PATIENT" 
   (	"MERGED_PATIENT_ID" NUMBER(19,0) NOT NULL, 
	"NHS_NUMBER" VARCHAR2(10),
	PRIMARY KEY(MERGED_PATIENT_ID)
   ) ;

--   ALTER TABLE "SIM_SACT_PATIENT" MODIFY ("MERGED_PATIENT_ID" NOT NULL ENABLE);
--   ALTER TABLE "SIM_SACT_PATIENT" ADD CONSTRAINT PK_SIM_SACT_PATIENT PRIMARY KEY (MERGED_PATIENT_ID);

--------------------------------------------------------
--  DDL for Table SIM_SACT_REGIMEN
--------------------------------------------------------

  CREATE TABLE "SIM_SACT_REGIMEN" 
   (	"MERGED_REGIMEN_ID" NUMBER(19,0) NOT NULL, 
	"MERGED_TUMOUR_ID" NUMBER(19,0), 
	"HEIGHT_AT_START_OF_REGIMEN" NUMBER(10,3), 
	"WEIGHT_AT_START_OF_REGIMEN" NUMBER(10,3), 
	"INTENT_OF_TREATMENT" VARCHAR2(1), 
	"DATE_DECISION_TO_TREAT" DATE, 
	"START_DATE_OF_REGIMEN" DATE, 
	"MAPPED_REGIMEN" VARCHAR2(500), 
	"CLINICAL_TRIAL" VARCHAR2(2), 
	"CHEMO_RADIATION" VARCHAR2(1), 
	"MERGED_PATIENT_ID" NUMBER(19,0), 
	"BENCHMARK_GROUP" VARCHAR2(100),
	PRIMARY KEY(MERGED_REGIMEN_ID)
   ) ;

--   ALTER TABLE "SIM_SACT_REGIMEN" MODIFY ("MERGED_REGIMEN_ID" NOT NULL ENABLE);
--   ALTER TABLE "SIM_SACT_REGIMEN" ADD CONSTRAINT PK_SIM_SACT_REGIMEN PRIMARY KEY (MERGED_REGIMEN_ID);

--------------------------------------------------------
--  DDL for Table SIM_SACT_TUMOUR
--------------------------------------------------------

  CREATE TABLE "SIM_SACT_TUMOUR" 
   (	"MERGED_TUMOUR_ID" NUMBER(19,0) NOT NULL, 
	"MERGED_PATIENT_ID" NUMBER(19,0), 
	"CONSULTANT_SPECIALITY_CODE" NUMBER(10,0), 
	"PRIMARY_DIAGNOSIS" VARCHAR2(6), 
	"MORPHOLOGY_CLEAN" VARCHAR2(5),
	PRIMARY KEY(MERGED_TUMOUR_ID)
   ) ;

--   ALTER TABLE "SIM_SACT_TUMOUR" MODIFY ("MERGED_TUMOUR_ID" NOT NULL ENABLE);
--   ALTER TABLE "SIM_SACT_TUMOUR" ADD CONSTRAINT PK_SIM_SACT_TUMOUR PRIMARY KEY (MERGED_TUMOUR_ID);
