--------------------------------------------------------
--  File created - Tuesday-April-25-2017   
--------------------------------------------------------
CREATE TABLE ZACE27SCORE 
(
  ZACE27SCOREID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY(ZACE27SCOREID)
);

CREATE TABLE ZALLRED 
(
  ZALLREDID NUMBER(19, 0) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, COSD_SCORE VARCHAR2(255) 
, COSD_STATUS VARCHAR2(255) 
, PRIMARY KEY 
  (
    ZALLREDID 
  )
);

CREATE TABLE ZBASIS 
(
  ZBASISID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZBASISID 
  )
 );

CREATE TABLE ZBEHAVIOUR 
(
  ZBEHAVIOURID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(64) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZBEHAVIOURID 
  )
 );

CREATE TABLE ZCANCERCAREPLANINTENT 
(
  ZCANCERCAREPLANINTENTID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZCANCERCAREPLANINTENTID 
  )
 );

CREATE TABLE ZCNSLOCATION 
(
  ZCNSLOCATIONID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZCNSLOCATIONID 
  )
 );

CREATE TABLE ZDEATHLOCATION 
(
  ZDEATHLOCATIONID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, COSDID VARCHAR2(255) 
, PRIMARY KEY 
  (
    ZDEATHLOCATIONID 
  )
 );

CREATE TABLE ZDIAGNOSTICROUTE 
(
  ZDIAGNOSTICROUTEID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, SCREENINGPROGRAMME NUMBER(4, 0) 
, SCREENDETECTED VARCHAR2(255) 
, COSDCODE VARCHAR2(255) 
, GRANULARCODE VARCHAR2(255) 
, PRIMARY KEY 
  (
    ZDIAGNOSTICROUTEID 
  )
 );

CREATE TABLE ZETHNICITY 
(
  ZETHNICITYID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZETHNICITYID 
  )
 );

CREATE TABLE ZGRADE 
(
  ZGRADEID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZGRADEID 
  )
 );

-- COMMENT ON COLUMN ZHISTOLOGYLOOKUP.DESCRIPTION IS 'THIS IS FOR AUTOCOMPLETION USE ONLY DO NOT USE ZHISTOLOGYLOOKUPID AS A FOREIGN KEY';

CREATE TABLE ZHISTOLOGYLOOKUP 
(
  ZHISTOLOGYLOOKUPID NUMBER(10, 0) NOT NULL  --'THIS IS FOR AUTOCOMPLETION USE ONLY DO NOT USE ZHISTOLOGYLOOKUPID AS A FOREIGN KEY'
, ZMORPHOLOGYID VARCHAR2(255) NOT NULL 
, ZBEHAVIOURID VARCHAR2(255) NOT NULL 
, DESCRIPTION VARCHAR2(255) NOT NULL 
, PRIMARY KEY 
  (
    ZHISTOLOGYLOOKUPID 
  )
 );

CREATE INDEX ZHISTOLOGYLOOKUP_MRP_BHV_IX ON ZHISTOLOGYLOOKUP (ZMORPHOLOGYID ASC, ZBEHAVIOURID ASC);

CREATE TABLE ZICD 
(
  ZICDID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, ZICDCLASSIFICATIONID NUMBER(19, 0) 
, ZICDGROUPID NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZICDID 
  )
 );

CREATE INDEX ZICD_EXPORTID_IX ON ZICD (EXPORTID ASC);

CREATE INDEX ZICD_ZICDGROUPID_IX ON ZICD (ZICDGROUPID ASC);

-- COMMENT ON COLUMN ZICDCLASSIFICATION.STARTDATE IS 'INFO ONLY - AUTOCOMPLETE USES ZICD STARTDATE';
-- COMMENT ON COLUMN ZICDCLASSIFICATION.ENDDATE IS 'INFO ONLY - AUTOCOMPLETE USES ZICD ENDDATE';

CREATE TABLE ZICDCLASSIFICATION 
(
  ZICDCLASSIFICATIONID NUMBER(19, 0) NOT NULL 
, SYMBOL VARCHAR2(255) NOT NULL 
, DESCRIPTION VARCHAR2(255) NOT NULL 
, STARTDATE DATE 	--'INFO ONLY - AUTOCOMPLETE USES ZICD STARTDATE';
, ENDDATE DATE 	--'INFO ONLY - AUTOCOMPLETE USES ZICD ENDDATE';
, PRIMARY KEY 
  (
    ZICDCLASSIFICATIONID 
  )
 );

CREATE INDEX ZICDCLASSIFICATION_SYMBOL_IX ON ZICDCLASSIFICATION (SYMBOL ASC);

CREATE TABLE ZLATERALITY 
(
  ZLATERALITYID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZLATERALITYID 
  )
 );

CREATE TABLE ZSEX 
(
  ZSEXID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZSEXID 
  )
);

CREATE TABLE ZSTAGE 
(
  ZSTAGEID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZSTAGEID 
  )
 );

CREATE TABLE ZTNMEDITION 
(
  ZTNMEDITIONID NUMBER(19, 0) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZTNMEDITIONID 
  )
 );

CREATE TABLE ZVITALSTATUS 
(
  ZVITALSTATUSID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZVITALSTATUSID 
  )
 );

CREATE TABLE ZYESNOUNKNOWN 
(
  ZYESNOUNKNOWNID VARCHAR2(255) NOT NULL 
, SHORTDESC VARCHAR2(255) 
, DESCRIPTION VARCHAR2(255) 
, EXPORTID VARCHAR2(255) 
, STARTDATE DATE 
, ENDDATE DATE 
, SORT NUMBER(10, 0) 
, PRIMARY KEY 
  (
    ZYESNOUNKNOWNID 
  )
);
