-- REM INSERTING into ZACE27SCORE
-- SET DEFINE OFF;
Insert into ZACE27SCORE (ZACE27SCOREID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('0','None',null,'0',null,null,1);
Insert into ZACE27SCORE (ZACE27SCOREID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('1','Mild',null,'1',null,null,2);
Insert into ZACE27SCORE (ZACE27SCOREID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('2','Moderate',null,'2',null,null,3);
Insert into ZACE27SCORE (ZACE27SCOREID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('3','Severe',null,'3',null,null,4);
Insert into ZACE27SCORE (ZACE27SCOREID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('9','Not known',null,'9',null,null,5);
