-- REM INSERTING into ZCANCERCAREPLANINTENT
-- SET DEFINE OFF;
Insert into ZCANCERCAREPLANINTENT (ZCANCERCAREPLANINTENTID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('9','Not known',null,'9',null,null,4);
Insert into ZCANCERCAREPLANINTENT (ZCANCERCAREPLANINTENTID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('C','Curative',null,'C',null,null,1);
Insert into ZCANCERCAREPLANINTENT (ZCANCERCAREPLANINTENTID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('X','No active treatment',null,'X',null,null,3);
Insert into ZCANCERCAREPLANINTENT (ZCANCERCAREPLANINTENTID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('Z','Non Curative',null,'Z',null,null,2);
