-- REM INSERTING into ZTNMEDITION
-- SET DEFINE OFF;
Insert into ZTNMEDITION (ZTNMEDITIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values (5,'5',null,'5',null,null,-1);
Insert into ZTNMEDITION (ZTNMEDITIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values (6,'6',null,'6',null,null,-1);
Insert into ZTNMEDITION (ZTNMEDITIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values (7,'7',null,'7',null,null,-1);
Insert into ZTNMEDITION (ZTNMEDITIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values (20,'UICC 5',null,'5U',null,null,null);
Insert into ZTNMEDITION (ZTNMEDITIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values (21,'UICC 6',null,'6U',null,null,null);
Insert into ZTNMEDITION (ZTNMEDITIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values (22,'UICC 7',null,'7U',null,null,null);
Insert into ZTNMEDITION (ZTNMEDITIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values (23,'AJCC 7',null,'7J',null,null,null);
Insert into ZTNMEDITION (ZTNMEDITIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values (24,'Unknown',null,'UNKNOWN',null,null,null);
