-- REM INSERTING into ZBEHAVIOUR
-- SET DEFINE OFF;
Insert into ZBEHAVIOUR (ZBEHAVIOURID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('0','BENIGN',null,'0',null,null,1);
Insert into ZBEHAVIOUR (ZBEHAVIOURID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('1','UNCERTAIN',null,'1',null,null,2);
Insert into ZBEHAVIOUR (ZBEHAVIOURID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('2','IN SITU',null,'2',null,null,3);
Insert into ZBEHAVIOUR (ZBEHAVIOURID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('3','MALIGNANT',null,'3',null,null,4);
Insert into ZBEHAVIOUR (ZBEHAVIOURID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('5','MICRO-INVASIVE',null,'5',null,null,5);
Insert into ZBEHAVIOUR (ZBEHAVIOURID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('6','MALIGNANT, METASTATIC/ SECONDARY SITE',null,'6',null,null,6);
Insert into ZBEHAVIOUR (ZBEHAVIOURID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('9','MALIGNANT, UNCERTAIN WHETHER PRIMARY OR METASTATIC',null,'9',null,null,7);
Insert into ZBEHAVIOUR (ZBEHAVIOURID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('X','UNKNOWN/INAPPLICABLE',null,'X',null,null,-1);
