-- REM INSERTING into ZDEATHLOCATION
-- SET DEFINE OFF;
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('1','HOSPITAL',null,'1',null,null,null,'10');
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('2','PRIVATE HOME',null,'4',null,null,null,'20');
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('3','HOSPICE NOS',null,'2',null,null,null,'30');
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('4','NURSING HOME',null,'5',null,null,null,null);
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('4077','NHS HOSPICE / SPECIALIST PALLIATIVE CARE UNIT',null,'2',null,null,null,'2');
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('4087','VOLUNTARY HOSPICE / SPECIALIST PALLIATIVE CARE UNIT',null,'3',null,null,null,'3');
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('4097','CARE HOME',null,'5',null,null,null,'40');
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('4107','PATIENT''S OWN HOME',null,'4',null,null,null,'21');
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('4117','OTHER PRIVATE RESIDENCE (E.G. RELATIVES HOME, CARERS HOME)',null,'4',null,null,null,'22');
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('4127','CARE HOME WITH NURSING',null,'5',null,null,null,'41');
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('4137','CARE HOME WITHOUT NURSING',null,'5',null,null,null,'42');
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('5','OTHER',null,'6',null,null,null,'50');
Insert into ZDEATHLOCATION (ZDEATHLOCATIONID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT,COSDID) values ('X','UNKNOWN',null,'X',null,null,null,null);
