-- REM INSERTING into ZYESNOUNKNOWN
-- SET DEFINE OFF;
Insert into ZYESNOUNKNOWN (ZYESNOUNKNOWNID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('8','N/A',null,'8',null,null,3);
Insert into ZYESNOUNKNOWN (ZYESNOUNKNOWNID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('9','X UNKNOWN',null,'9',null,null,4);
Insert into ZYESNOUNKNOWN (ZYESNOUNKNOWNID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('N','NO',null,'N',null,null,2);
Insert into ZYESNOUNKNOWN (ZYESNOUNKNOWNID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('Y','YES',null,'Y',null,null,1);
