-- REM INSERTING into ZVITALSTATUS
-- SET DEFINE OFF;
Insert into ZVITALSTATUS (ZVITALSTATUSID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('A','Alive',null,'A',null,null,1);
Insert into ZVITALSTATUS (ZVITALSTATUSID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('D','Dead',null,'D',null,null,2);
Insert into ZVITALSTATUS (ZVITALSTATUSID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('X','Exit Posting',null,'X',null,null,3);
