-- REM INSERTING into ZSEX
-- SET DEFINE OFF;
Insert into ZSEX (ZSEXID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('0','X NOT KNOWN',null,'0',null,null,5);
Insert into ZSEX (ZSEXID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('1','MALE',null,'1',null,null,1);
Insert into ZSEX (ZSEXID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('2','FEMALE',null,'2',null,null,2);
Insert into ZSEX (ZSEXID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('4000','INDETERMINATE',null,'9',null,null,-1);
Insert into ZSEX (ZSEXID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('9','NOT SPECIFIED',null,'9',null,null,3);
