-- REM INSERTING into ZLATERALITY
-- SET DEFINE OFF;
Insert into ZLATERALITY (ZLATERALITYID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('8','NOT APPLICABLE',null,'8',null,null,5);
Insert into ZLATERALITY (ZLATERALITYID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('9','X NOT KNOWN',null,'9',null,null,6);
Insert into ZLATERALITY (ZLATERALITYID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('B','BILATERAL',null,'B',null,null,4);
Insert into ZLATERALITY (ZLATERALITYID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('L','LEFT',null,'L',null,null,1);
Insert into ZLATERALITY (ZLATERALITYID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('M','MIDLINE',null,'M',null,null,3);
Insert into ZLATERALITY (ZLATERALITYID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('R','RIGHT',null,'R',null,null,2);
Insert into ZLATERALITY (ZLATERALITYID,SHORTDESC,DESCRIPTION,EXPORTID,STARTDATE,ENDDATE,SORT) values ('Z','Z','Outdated or invalid code Z','Z',null,null,-1);
